### ISSUE TITLE
"Analyzing" graphics low quality

### ISSUE THREAD

**Issue by mglowacki100** [inovance/traide-issues-public#21]
Trivial issue - "Analyzing" graphics animation in low quality.

**Comment by devjustin** [comment]
Most likely eplacing the current .gif with an SVG in the next update. 

Here is a nice set under the MIT License http://samherbert.net/svg-loaders/

I am leaning towards slowing down the audio histogram in the top left and adding some more bars.

**Comment by devjustin** [comment]
Put in an SVG
Deployed 04/10 TRAIDE v2.0.1
