### ISSUE TITLE
Contrast issues

### ISSUE THREAD

**Issue by mglowacki100** [inovance/traide-issues-public#23]
Strategy performance chart - red on gray (O,H,L,C) doesn't look good. I suggest use other kind of gray or style similar to date picker (black frame, black O, no fill or very slight).

**Comment by devjustin** [comment]
It looks a lot better without the background color. What do you think?


![image](https://cloud.githubusercontent.com/assets/4055984/6988261/a84d1ecc-da1d-11e4-89f3-e69c267fd726.png)

**Comment by devjustin** [comment]
Deployed 04/10 TRAIDE v2.0.1

**Comment by mglowacki100** [comment]
Looks good.
